highlighter: rouge
permalink: '/:title'
title: 'Dave Stevens'
description: 'Engineering Leader based in Denver, CO'
meta_description: 'Dave Stevens is an Engineering Leader based in Denver, CO'
logo: 'http://dstevens.io/images/social.png'
page_title: 'Dave Stevens'
base_url: 'http://dstevens.io'
github: 'dstevensio'
medium: '@dstevensio'
linkedin: 'daveastevens'
email: 'ds@dstevens.io'
google_analytics_id: 'UA-37398643-1'
twitter: 'davefromreading'
