highlighter: rouge
permalink: '/:title'
title: 'Dave Stevens'
description: 'An Anglo-American Software Engineer in Las Vegas, NV. Web Engineering, JavaScript, nodeJS, hapi.js'
meta_description: 'Dave Stevens is an Anglo-American Software Engineer in Las Vegas, NV. Web Engineering, JavaScript, nodeJS, hapi.js'
logo: 'http://dstevens.io/images/social.png'
page_title: 'Dave Stevens: @dstevensio'
base_url: 'http://dstevens.io'
github: 'dstevensio'
medium: '@dstevensio'
linkedin: 'daveastevens'
email: 'ds@dstevensio'
google_analytics_id: 'UA-37398643-1'
